const ActionType = {
    ADMIN: "ADMIN",
    PRODUCTS:"PRODUCTS",
    ORDERS: "ORDERS",
    EDITPRODUCT:"EDITPRODUCT",
    SHOWORDERDETAILS : "SHOWORDERDETAILS",
    ORDERDELIVERED : "ORDERDELIVERED",
    SELLER : "SELLER"
}

export default ActionType;